### ISSUE TITLE
Invoke-Phant0m detecting

### ISSUE THREAD

**Issue by cybervaca** [hlldz/Phant0m#2]
Hello, first of all congratulations on invoke-phat0m. I would like to know if there would be any way to detect that invoke-phat0m is running.

Thank you very much.

**Comment by hlldz** [comment]
Hi,

Thank you for your interest.

Basically, you need to watch endpoint system for detecting attacks like Invoke-Phant0m. I would recommend you to check this resources;

https://securitylogsdotorg.files.wordpress.com/2017/06/bsides-athens-sysmon-final.pdf
https://twitter.com/inslainity/status/867172350457925632

**Comment by cybervaca** [comment]
thx u so much dude.
