### ISSUE TITLE
How can i restart the event log service

### ISSUE THREAD

**Issue by arjing** [hlldz/Phant0m#3]
Hello,
How can i restart the event log service？

best

**Comment by hlldz** [comment]
Hi,

How to Start/Stop Windows Event Log Service, http://computerstepbystep.com/windows_event_log_service.html

Using the Restart-Service Cmdlet (PowerShell), https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-powershell-1.0/ee176942(v=technet.10)
