### ISSUE TITLE
A working version for latest windows version...

### ISSUE THREAD

**Issue by ghost** [hlldz/Phant0m#8]
https://github.com/codecastor/WinEventSuspend

This is basically the same idea as it was implemented in Phant0m, but that one works. Instead of killind the Service's threads, we suspend them. This is because in the latest windows version, the threads are re-created as soon as they are killed.

**Comment by hlldz** [comment]
1- In which version did you encounter this behavior? Try again both on the system with all the updates/upgrades installed and on the system with the previous distribution version installed, everything works correctly. Killed threads are not recreated. So, can you provide proof that Phant0m is not working?

2- Although the suspending of the threads seems to be working but all the logs will appear again as soon as the threads continue. That's why Phant0m kills threads and doesn't suspend since its first version. You can test this situation with Security logs.

**Comment by arsscriptum** [comment]
Hi mate, thanks for your reply. I will anwser your questions in my reply that I will send in 1 hour. I will grab all the and details and communicate them to you. Stay tuned. :)

**Comment by ghost** [comment]
Hi mate, thanks for your reply. I will anwser your questions in my reply that I will send in 1 hour. I will grab all the and details and communicate them to you. Stay tuned. :)

**Comment by codecastor** [comment]
Im sorry if it takes more time, but I will reply tonight.

**Comment by ghost** [comment]
## Problem with PHANTOM - DETECTION / HIGHLY VISIBLE 
It actually Kills the PARENT service. So it is super easy to detect that it was run. Not only that, if you are to kill the parent service, why bother with the child threads at all, just stop the service right away... 

I need to comeback on the issue I have with the technique in Phantom. After more testing, the problem is not that the threads are re-created. (They are, but if you kill them one-by-one) with long delays in between while there is event loaging)
But the REAL problem is that when Phantom KILLs all the child threads of the Event Service, the Event Service essentially dies as well (without us killing the process).

1) I use my test application to LIST the EventMgr PID and Child Threads (list only).
2) In Process Explorer, I see the THREADS
3) I can log events...
4) Using PHANTOM, I terminate the threads using method 1
5) In Process Explorer, I see the THREADS BEING DEAD, but ALSO, the parent is now dead.
6) In Services, I see the Event Log Service is now DEAD

## Problem

OBVIOUSLY, the issue here is that any user with a nose will see that the event service is down and it will be in a position to restart it. or that situation will be detected.

[https://github.com/codecastor/WinEventSuspend/blob/main/data/Bug.gif](https://github.com/codecastor/WinEventSuspend/blob/main/data/Bug.gif)


So in the end, if you want to stay discreet, disable the events without being detected, SUSPEND the threads

**Comment by hlldz** [comment]
I ran the retests and did not encounter the "PROBLEM" you mentioned.

Phant0m does not kill the process, it only detects and kills threads belonging to the Event Log service. You can read the code and readme.md. So you can fully understand the concept and how it works.

At the moment I don't see enough evidence for what you describe as "PROBLEM".

**Comment by ghost** [comment]
I understand that Phantom does not kill the parent process, it is just terminating the threads. The issues I raised, and the one you can see in the videoI shared, is that once you terminate all the threads belonging to a particular process, that process will itself be terminated by the OS. It is not an issue in Phantom per say, just that when you use it, it ends up killing the service... That's all.  it's easily reproduceable, even just with Process Monitor, if you kill all the threads manually , the paretn service will terminate. Hence, the preference to keep them alive with suspend.

BTW.: I have updated my test projects README and changed the wording.

I just wanted to communicate this. Thanks for your time
Have a nice evening, happy NY

**Comment by codecastor** [comment]
I just wanted to communicate this. Thanks for your time
Have a nice evening, happy NY
